import Head from "next/head";
import Sidebar from "./Home/Sidebar";
import Homepage from "./Home/Homepage";

export default function Home() {
  return (
    <>
      <Head>
        <title>Drive Cleaner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex">
        <div className="max-w-xs h-screen md:min-w-[20rem]">
          <Sidebar />
        </div>
        <div className="flex-1 text-white bg-[#343541]">
          <Homepage />
        </div>
      </div>
    </>
  );
}
